before_script:
  # Install Ansible
  - sudo apt-get install software-properties-common -y
  - sudo apt-add-repository ppa:ansible/ansible -y 
  - sudo apt-get update
  - sudo apt-get install ansible -y

docker_setup:
  script:
    - sudo ansible-playbook docker.yaml -i hosts.ini
  stage: docker_setup
  tags:
    - shell
    - pm01
  only:
    - tags
    - triggers

gitlab_setup:
  script:
    - sudo ansible-playbook gitlab.yaml -i hosts.ini
  stage: gitlab_setup
  tags:
    - shell
    - pm01
  only:
    - tags
    - triggers

stages:
  - docker_setup
  - gitlab_setup
