before_script:
  # Install Ansible
  - sudo apt-get install software-properties-common -y
  - sudo apt-add-repository ppa:ansible/ansible -y 
  - sudo apt-get update
  - sudo apt-get install ansible -y

deploy:
  script:
    - ansible-playbook docker.yaml -i hosts.ini
  stage: deploy
  tags:
    - shell
    - pm01
  only:
    - tags
    - triggers

stages:
  - deploy
